server:
  port: 7070
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://bvaqqfujqjblhk:3e5235049f2e70bc95fe929cf4b4a75b7ee3a908b6fc5805877627c48743f4b9@ec2-34-232-191-133.compute-1.amazonaws.com:5432/d1dufpo38scebs
    username: bvaqqfujqjblhk
    password: 3e5235049f2e70bc95fe929cf4b4a75b7ee3a908b6fc5805877627c48743f4b9


  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto Criado pela Dio-Santander